<?xml version="1.0"?>

<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="komodo2_robot" description="Komodo2 Robot">
	<xacro:property name="M_PI" value="3.1415926535897931" />
        
      <link name="base_footprint"/>
  
 <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0.00 0.00 0.1275" rpy="0.0 0.0 0.0"/>
  </joint> 

  <link
    name="base_link">
    <inertial>
      <origin
        xyz="0.0030152 0.00057861 0.0749"
        rpy="0 0 0" />
      <mass
        value="20.0058" />
      <inertia
        ixx="0.025582"
        ixy="0.0010034"
        ixz="-0.0041152"
        iyy="0.086418"
        iyz="-3.8058E-05"
        izz="0.091994" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://komodo2_description/mesh/base.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://komodo2_description/mesh/base.STL" />
      </geometry>
    </collision>
  </link>

  <link
    name="rear_left_wheel_link">
    <inertial>
      <origin
        xyz="9.8684E-07 -9.3003E-05 -1.8753E-05"
        rpy="0 0 0" />
      <mass
        value="2.6829" />
      <inertia
        ixx="0.012758"
        ixy="8.7952E-09"
        ixz="-1.0406E-07"
        iyy="0.023277"
        iyz="2.0115E-06"
        izz="0.012755" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://komodo2_description/mesh/wheel.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="${M_PI/2} 0 0" />
      <geometry>
	<!--  <mesh filename="package://komodo2_description/mesh/wheel.STL" /> -->
	  <cylinder  length="0.05" radius="0.127"/> 
      </geometry>
    </collision>
  </link>
  <joint
    name="rear_left_wheel_joint"
    type="continuous">
    <origin
      xyz="-0.165 0.18955 0"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="rear_left_wheel_link" />
    <axis
      xyz="0 1 0" />
  </joint>
  <link
    name="front_left_wheel_link">
    <inertial>
      <origin
        xyz="9.8687E-07 -9.3003E-05 -1.8753E-05"
        rpy="0 0 0" />
      <mass
        value="2.6829" />
      <inertia
        ixx="0.012758"
        ixy="8.7932E-09"
        ixz="-1.0406E-07"
        iyy="0.023277"
        iyz="2.0115E-06"
        izz="0.012755" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://komodo2_description/mesh/wheel.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="${M_PI/2} 0 0" />
      <geometry>
	<!--  <mesh filename="package://komodo2_description/mesh/wheel.STL" /> -->
	  <cylinder  length="0.05" radius="0.127"/> 
      </geometry>
    </collision>
  </link>
  <joint
    name="front_left_wheel_joint"
    type="continuous">
    <origin
      xyz="0.165 0.18955 0"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="front_left_wheel_link" />
    <axis
      xyz="0 1 0" />
  </joint>
  <link
    name="rear_right_wheel_link">
    <inertial>
      <origin
        xyz="-9.8675E-07 9.3004E-05 -1.8753E-05"
        rpy="0 0 0" />
      <mass
        value="2.6829" />
      <inertia
        ixx="0.012758"
        ixy="8.801E-09"
        ixz="1.0405E-07"
        iyy="0.023277"
        iyz="-2.0115E-06"
        izz="0.012755" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://komodo2_description/mesh/wheel.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="${M_PI/2} 0 0" />
      <geometry>
	<!--  <mesh filename="package://komodo2_description/mesh/wheel.STL" /> -->
	  <cylinder  length="0.05" radius="0.127"/> 
      </geometry>
    </collision>
  </link>
  <joint
    name="rear_right_wheel_joint"
    type="continuous">
    <origin
      xyz="-0.165 -0.18955 0"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="rear_right_wheel_link" />
    <axis
      xyz="0 1 0" />
  </joint>
  <link
    name="front_right_wheel_link">
    <inertial>
      <origin
        xyz="-9.867E-07 9.3004E-05 -1.8753E-05"
        rpy="0 0 0" />
      <mass
        value="2.6829" />
      <inertia
        ixx="0.012758"
        ixy="8.8036E-09"
        ixz="1.0405E-07"
        iyy="0.023277"
        iyz="-2.0115E-06"
        izz="0.012755" />
    </inertial>
    <visual>
      <origin
        xyz="0 0 0"
        rpy="0 0 0" />
      <geometry>
        <mesh
          filename="package://komodo2_description/mesh/wheel.STL" />
      </geometry>
      <material
        name="">
        <color
          rgba="0.79216 0.81961 0.93333 1" />
      </material>
    </visual>
    <collision>
      <origin
        xyz="0 0 0"
        rpy="${M_PI/2} 0 0" />
      <geometry>
	<!--  <mesh filename="package://komodo2_description/mesh/wheel.STL" /> -->
	  <cylinder  length="0.05" radius="0.127"/> 
      </geometry>
    </collision>
  </link>
  <joint
    name="front_right_wheel_joint"
    type="continuous">
    <origin
      xyz="0.165 -0.18955 0"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="front_right_wheel_link" />
    <axis
      xyz="0 1 0" />
  </joint>
  <link
    name="laser_link" />
  <joint
    name="laser_joint"
    type="fixed">
    <origin
      xyz="0.233497501055752 0 0.141334654748157"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="laser_link" />
    <axis
      xyz="0 0 0" />
  </joint>
  <link
    name="rgb_cam_link" />
  <joint
    name="rgb_cam_joint"
    type="fixed">
    <origin
      xyz="0.25425 0.0875 0.1"
      rpy="0 0 0" />
    <parent
      link="base_link" />
    <child
      link="rgb_cam_link" />
    <axis
      xyz="0 0 0" />
  </joint>
  <link
    name="rear_urf_link" />
  <joint
    name="rear_urf_joint"
    type="fixed">
    <origin
      xyz="-0.2745 0 0.108"
      rpy="0 0 3.1416" />
    <parent
      link="base_link" />
    <child
      link="rear_urf_link" />
    <axis
      xyz="0 0 0" />
  </joint>
  <link
    name="right_urf_link" />
  <joint
    name="right_urf_joint"
    type="fixed">
    <origin
      xyz="-0.029313 -0.13725 0.13851"
      rpy="0 -2.0713E-16 -1.5708" />
    <parent
      link="base_link" />
    <child
      link="right_urf_link" />
    <axis
      xyz="0 0 0" />
  </joint>
  <link
    name="left_urf_link" />
  <joint
    name="left_urf_joint"
    type="fixed">
    <origin
      xyz="-0.029313 0.13725 0.13851"
      rpy="0 2.0713E-16 1.5708" />
    <parent
      link="base_link" />
    <child
      link="left_urf_link" />
    <axis
      xyz="0 0 0" />
  </joint>
 

  
  
  
  
  
<!--
License: Apache 2.0. See LICENSE file in root directory.
Copyright(c) 2017 Intel Corporation. All Rights Reserved

the following is the URDF model for the Intel RealSense 430 camera, in it's
aluminum peripherial evaluation case.
-->
   
  <!-- depth camera -->
  <xacro:property name="r430_cam_depth_to_left_ir_offset" value="-0.025"/>
  <xacro:property name="r430_cam_depth_to_right_ir_offset" value="0.025"/>
  <xacro:property name="r430_cam_depth_to_fisheye_offset" value="0.042"/>

  <!-- The following values model the aluminum peripherial case for the
    R430 camera, with the camera joint represented by the actual 
    peripherial camera tripod mount -->
  <xacro:property name="r430_cam_width" value="0.105"/>
  <xacro:property name="r430_cam_height" value="0.039"/>
  <xacro:property name="r430_cam_depth" value="0.019"/>
  <xacro:property name="r430_cam_mount_from_center_offset" value=".0275"/>

  <!-- The following offset is relative the the physical R430 camera peripherial
    camera tripod mount -->
  <xacro:property name="r430_cam_depth_px" value="0.00"/>
  <xacro:property name="r430_cam_depth_py" value="-0.035"/>
  <xacro:property name="r430_cam_depth_pz" value="0.028"/>  

             <!-- camera body, with origin at bottom screw mount -->
    <joint name="camera_joint" type="fixed">
      <origin
      xyz="0.25525 0.0006082 0.063584"
      rpy="0 0 0" />
    <parent
      link="base_link" />
      <child link="camera_link" />
    </joint>

    <link name="camera_link">
      <visual>
      <origin xyz="0 ${-r430_cam_mount_from_center_offset} ${r430_cam_height/2}" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <box size="${r430_cam_width} ${r430_cam_height} ${r430_cam_depth}"/>
          <!--<mesh filename="package://realsense_ros_camera/meshes/r430/r430.dae" />-->
        </geometry>
        <material name="aluminum"/>
      </visual>
      <collision>
        <origin xyz="0.0 0.0 ${r430_cam_height/2}" rpy="0 0 0"/>
        <geometry>
        <box size="${r430_cam_depth} ${r430_cam_width} ${r430_cam_height}"/>
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.564" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>
   
    <!-- camera depth joints and links -->
    <joint name="camera_depth_joint" type="fixed">
      <origin xyz="${r430_cam_depth_px} ${r430_cam_depth_py} ${r430_cam_depth_pz}" rpy="0 0 0"/>
      <parent link="camera_link"/>
      <child link="camera_depth_frame" />
    </joint>
    <link name="camera_depth_frame"/>

    <joint name="camera_depth_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_depth_frame" />
      <child link="camera_depth_optical_frame" />
    </joint>
    <link name="camera_depth_optical_frame"/>
      
    <!-- camera left IR joints and links -->
    <joint name="camera_left_ir_joint" type="fixed">
      <origin xyz="0 ${r430_cam_depth_to_left_ir_offset} 0" rpy="0 0 0" />
      <parent link="camera_depth_frame" />
      <child link="camera_left_ir_frame" />
    </joint>
    <link name="camera_left_ir_frame"/>

    <joint name="camera_left_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_left_ir_frame" />
      <child link="camera_left_ir_optical_frame" />
    </joint>
    <link name="camera_left_ir_optical_frame"/>

    <!-- camera right IR joints and links -->
    <joint name="camera_right_ir_joint" type="fixed">
      <origin xyz="0 ${r430_cam_depth_to_right_ir_offset} 0" rpy="0 0 0" />
      <parent link="camera_depth_frame" />
      <child link="camera_right_ir_frame" />
    </joint>
    <link name="camera_right_ir_frame"/>

    <joint name="camera_right_ir_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_right_ir_frame" />
      <child link="camera_right_ir_optical_frame" />
    </joint>
    <link name="camera_right_ir_optical_frame"/>

    <!-- camera fisheye joints and links -->
    <joint name="camera_fisheye_joint" type="fixed">
      <origin xyz="0 ${r430_cam_depth_to_fisheye_offset} 0" rpy="0 0 0" />
      <parent link="camera_depth_frame" />
      <child link="camera_fisheye_frame" />
    </joint>
    <link name="camera_fisheye_frame"/>

    <joint name="camera_fisheye_optical_joint" type="fixed">
      <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
      <parent link="camera_fisheye_frame" />
      <child link="camera_fisheye_optical_frame" />
    </joint>
    <link name="camera_fisheye_optical_frame"/>

</robot>
