
robot_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

mobile_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'left_wheel_joint'
  right_wheel: 'right_wheel_joint'
  publish_rate: 50.0               # default: 50
  pose_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.03]
  twist_covariance_diagonal: [0.01, 0.01, 0.01, 0.01, 0.01, 0.03]

  # Wheel separation and diameter. These are both optional.
  # diff_drive_controller will attempt to read either one or both from the
  # URDF if not specified as a parameter
  wheel_separation : 0.3284
  wheel_radius : 0.09
  # slip_factor: 1.0

  # Wheel separation and radius multipliers
  wheel_separation_multiplier: 1.0 # default: 1.0
  wheel_radius_multiplier    : 1.0 # default: 1.0

  # Velocity commands timeout [s], default 0.5
  cmd_vel_timeout: 1.0

  enable_odom_tf: true

  # Base frame_id
  base_frame_id: base_footprint

  # Velocity and acceleration limits
  # Whenever a min_* is unspecified, default to -max_*
  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 0.4  # m/s
      min_velocity           : -0.2 # m/s
      has_acceleration_limits: true
      max_acceleration       : 0.15  # m/s^2
      min_acceleration       : -0.15 # m/s^2
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.0  # rad/s
      has_acceleration_limits: true
      max_acceleration       : 0.5  # rad/s^2